### ISSUE TITLE
add LICENSE file

### ISSUE THREAD

**Issue by MahmoudMabrok** [brookmg/Kuwas#7]

**Comment by brookmg** [comment]
The whole project is governed by the [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) license. It stated on the README file and also inside each source code file. But I will add the License file anyway 👍🏾

**Comment by MahmoudMabrok** [comment]
@brookmg  when u add it informe me please

**Comment by brookmg** [comment]
I have added a license file https://github.com/brookmg/Kuwas/commit/9008dc071c465da61dbd9e7b217b6e91692db574, @MahmoudMabrok
